# Generated by Django 6.0.2 on 2026-03-11 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customerpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpdf',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_documents', to='app.customer'),
        ),
    ]
